### ISSUE TITLE
No validation of tenant id in UI

### ISSUE THREAD

**Issue by knstvk** [cuba-platform/multitenancy-addon#21]
### Environment

- Platform version: 7.0
- Addon version: 1.3-SNAPSHOT

### Description of the bug or enhancement

If you create `tenant-a` tenant, you will have an exception on login (which also does not describe the cause):
```
09:05:05.646 ERROR c.h.c.s.a.AuthenticationServiceBean     - Login error
java.lang.IllegalStateException: Tenant id is not valid: tenant-a
	at com.haulmont.addon.sdbmt.core.sys.MultiTenancySecurityHandler.compileTenantConstraints(MultiTenancySecurityHandler.java:104) ~[sdbmt-core-1.3-SNAPSHOT.jar:na]
	at com.haulmont.addon.sdbmt.core.sys.MultiTenancySecurityHandler.compileConstraints(MultiTenancySecurityHandler.java:90) ~[sdbmt-core-1.3-SNAPSHOT.jar:na]
```

**Comment by NikitaShchienko** [comment]
Can't reproduce
